name: main
version: '1.0.0'
main: _RedGold__.main.Main
api-version: '1.21'
load: STARTUP
authors: [ _RedGold__ ]
depend: [ LuckPerms, ProtocolLib ]

permissions:
  Main.user:
    default: true
  Main.plus:
    default: false
  Main.admin:
    default: false
    children:
      - Main.plus
  Main.owner:
    default: false
    children:
      - Main.plus
      - Main.admin
